DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmw0QGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2ODUwMTQ2ODR9.HC-5Xq3YsopbAO_K0QJiF2v8SNMoY1jaMf17xbqQUYg